import { Metadata } from 'next';
import AdminAside from '@/components/admin/aside/AdminAside';
import { redirect } from '@/i18n/navigation';

export const metadata: Metadata = {
  title: "Ecommerce admin panel",
  description: "Generated by create next app",

};

export default async function AdminLayout({
                                           children,
                                         }: Readonly<{
  children: React.ReactNode;

}>) {
  return (
    <>
      <div className={'admin-panel flex mx-auto w-[1300px] max-w-full gap-8'}>
       <AdminAside />
        <div className={'flex-grow'}>
          {children}
        </div>
      </div>
    </>
  );
}
