import type {Metadata} from "next";
import {Open_Sans} from "next/font/google";
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import '../global.css';
import {hasLocale, NextIntlClientProvider} from "next-intl";
import {routing} from "@/i18n/routing";
import {notFound} from "next/navigation";
import { ToastContainer } from 'react-toastify';
import 'react-quill-new/dist/quill.snow.css';
import {ThemeProvider} from "@/components/admin/themeProvider/ThemeProvider";


const openSansFont = Open_Sans({
    subsets: ['latin', 'cyrillic'],
    variable: '--font-open-sans',
});


export const metadata: Metadata = {
    title: "Ecommerce admin panel",
    description: "Generated by create next app",

};

export default async function RootLayout({
                                       children, params
                                   }: Readonly<{
    children: React.ReactNode;
    params: Promise<{locale: string}>;
}>) {
    const {locale} = await params;
    if (!hasLocale(routing.locales, locale)) {
        notFound();
    }
    // Inline script runs BEFORE React hydration to set the correct theme
    // class on <html>, preventing a flash of the wrong theme (FOUC).
    const themeInitScript = `
(function() {
  try {
    var stored = localStorage.getItem('admin-theme');
    var theme = (stored === 'light' || stored === 'dark')
      ? stored
      : (window.matchMedia && window.matchMedia('(prefers-color-scheme: dark)').matches ? 'dark' : 'light');
    if (theme === 'dark') {
      document.documentElement.classList.add('dark');
      document.documentElement.style.colorScheme = 'dark';
    } else {
      document.documentElement.style.colorScheme = 'light';
    }
  } catch (e) {}
})();
`;

    return (
        <html lang={locale} suppressHydrationWarning>
        <head>
            <script dangerouslySetInnerHTML={{ __html: themeInitScript }} />
        </head>
        <body
            className={`${openSansFont.variable} antialiased`}
        >
        <NextIntlClientProvider>
            <ThemeProvider>
                <main>
                    {children}
                </main>
            </ThemeProvider>
        </NextIntlClientProvider>
        <ToastContainer
            position="top-right"
            theme="colored"
            autoClose={4000}
            newestOnTop
            pauseOnHover
        />
        </body>
        </html>
    );
}
