import type {Metadata} from "next";
import {Open_Sans} from "next/font/google";
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import '../global.css';
import {hasLocale, NextIntlClientProvider} from "next-intl";
import {routing} from "@/i18n/routing";
import {notFound} from "next/navigation";
import { ToastContainer } from 'react-toastify';
import 'react-quill-new/dist/quill.snow.css';


const openSansFont = Open_Sans({
    subsets: ['latin', 'cyrillic'],
    variable: '--font-open-sans',
});


export const metadata: Metadata = {
    title: "Ecommerce admin panel",
    description: "Generated by create next app",

};

export default async function RootLayout({
                                       children, params
                                   }: Readonly<{
    children: React.ReactNode;
    params: Promise<{locale: string}>;
}>) {
    const {locale} = await params;
    if (!hasLocale(routing.locales, locale)) {
        notFound();
    }
    return (
        <html lang={locale}>
        <body
            className={`${openSansFont.variable} antialiased`}
        >
        <NextIntlClientProvider>
            <main>
                {children}
            </main>
        </NextIntlClientProvider>
        <ToastContainer />
        </body>
        </html>
    );
}
